export const bankConstants = {
    ADD_BANK_REQUEST: 'ADD_BANK_REQUEST',
    ADD_BANK_SUCCESS: 'ADD_BANK_SUCCESS',
    ADD_BANK_FAILURE: 'ADD_BANK_FAILURE',

    UPDATE_BANK_REQUEST: 'UPDATE_BANK_REQUEST',
    UPDATE_BANK_SUCCESS: 'UPDATE_BANK_SUCCESS',
    UPDATE_BANK_FAILURE: 'UPDATE_BANK_FAILURE',

    GET_ALL_BANKS_REQUEST: 'GET_ALL_BANKS_REQUEST',
    GET_ALL_BANKS_SUCCESS: 'GET_ALL_BANKS_SUCCESS',
    GET_ALL_BANKS_FAILURE: 'GET_ALL_BANKS_FAILURE',

    GET_BANKS_WITH_COUPON_PRICES_REQUEST: 'GET_BANKS_WITH_COUPON_PRICES_REQUEST',
    GET_BANKS_WITH_COUPON_PRICES_SUCCESS: 'GET_BANKS_WITH_COUPON_PRICES_SUCCESS',
    GET_BANKS_WITH_COUPON_PRICES_FAILURE: 'GET_BANKS_WITH_COUPON_PRICES_FAILURE',

    GET_USER_BANKS_REQUEST: 'GET_USER_BANKS_REQUEST',
    GET_USER_BANKS_SUCCESS: 'GET_USER_BANKS_SUCCESS',
    GET_USER_BANKS_FAILURE: 'GET_USER_BANKS_FAILURE',

    DELETE_BANK_REQUEST: 'DELETE_BANK_REQUEST',
    DELETE_BANK_SUCCESS: 'DELETE_BANK_SUCCESS',
    DELETE_BANK_FAILURE: 'DELETE_BANK_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_BANK: 'SELECT_BANK',

};