export const bankCardConstants = {
    ADD_BANK_CARD_REQUEST: 'ADD_BANK_CARD_REQUEST',
    ADD_BANK_CARD_SUCCESS: 'ADD_BANK_CARD_SUCCESS',
    ADD_BANK_CARD_FAILURE: 'ADD_BANK_CARD_FAILURE',

    UPDATE_BANK_CARD_REQUEST: 'UPDATE_BANK_CARD_REQUEST',
    UPDATE_BANK_CARD_SUCCESS: 'UPDATE_BANK_CARD_SUCCESS',
    UPDATE_BANK_CARD_FAILURE: 'UPDATE_BANK_CARD_FAILURE',

    GET_ALL_BANK_CARDS_REQUEST: 'GET_ALL_BANK_CARDS_REQUEST',
    GET_ALL_BANK_CARDS_SUCCESS: 'GET_ALL_BANK_CARDS_SUCCESS',
    GET_ALL_BANK_CARDS_FAILURE: 'GET_ALL_BANK_CARDS_FAILURE',

    GET_USER_BANK_CARDS_REQUEST: 'GET_USER_BANK_CARDS_REQUEST',
    GET_USER_BANK_CARDS_SUCCESS: 'GET_USER_BANK_CARDS_SUCCESS',
    GET_USER_BANK_CARDS_FAILURE: 'GET_USER_BANK_CARDS_FAILURE',

    DELETE_BANK_CARD_REQUEST: 'DELETE_BANK_CARD_REQUEST',
    DELETE_BANK_CARD_SUCCESS: 'DELETE_BANK_CARD_SUCCESS',
    DELETE_BANK_CARD_FAILURE: 'DELETE_BANK_CARD_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_BANK_CARD: 'SELECT_BANK_CARD',

};