export const branchConstants = {
    ADD_BRANCH_REQUEST: 'ADD_BRANCH_REQUEST',
    ADD_BRANCH_SUCCESS: 'ADD_BRANCH_SUCCESS',
    ADD_BRANCH_FAILURE: 'ADD_BRANCH_FAILURE',

    UPDATE_BRANCH_REQUEST: 'UPDATE_BRANCH_REQUEST',
    UPDATE_BRANCH_SUCCESS: 'UPDATE_BRANCH_SUCCESS',
    UPDATE_BRANCH_FAILURE: 'UPDATE_BRANCH_FAILURE',

    GET_ALL_BRANCHS_REQUEST: 'GET_ALL_BRANCHS_REQUEST',
    GET_ALL_BRANCHS_SUCCESS: 'GET_ALL_BRANCHS_SUCCESS',
    GET_ALL_BRANCHS_FAILURE: 'GET_ALL_BRANCHS_FAILURE',

    GET_BANK_BRANCHES_REQUEST: 'GET_BANK_BRANCHES_REQUEST',
    GET_BANK_BRANCHES_SUCCESS: 'GET_BANK_BRANCHES_SUCCESS',
    GET_BANK_BRANCHES_FAILURE: 'GET_BANK_BRANCHES_FAILURE',

    GET_USER_BRANCHS_REQUEST: 'GET_USER_BRANCHS_REQUEST',
    GET_USER_BRANCHS_SUCCESS: 'GET_USER_BRANCHS_SUCCESS',
    GET_USER_BRANCHS_FAILURE: 'GET_USER_BRANCHS_FAILURE',

    DELETE_BRANCH_REQUEST: 'DELETE_BRANCH_REQUEST',
    DELETE_BRANCH_SUCCESS: 'DELETE_BRANCH_SUCCESS',
    DELETE_BRANCH_FAILURE: 'DELETE_BRANCH_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_BRANCH: 'SELECT_BRANCH',

};