export const couponConstants = {
    ADD_COUPON_REQUEST: 'ADD_COUPON_REQUEST',
    ADD_COUPON_SUCCESS: 'ADD_COUPON_SUCCESS',
    ADD_COUPON_FAILURE: 'ADD_COUPON_FAILURE',

    CREATE_COUPON_MOBILE_PAYMENT_REQUEST: 'CREATE_COUPON_MOBILE_PAYMENT_REQUEST',
    CREATE_COUPON_MOBILE_PAYMENT_SUCCESS: 'CREATE_COUPON_MOBILE_PAYMENT_SUCCESS',
    CREATE_COUPON_MOBILE_PAYMENT_FAILURE: 'CREATE_COUPON_MOBILE_PAYMENT_FAILURE',

    UPDATE_COUPON_REQUEST: 'UPDATE_COUPON_REQUEST',
    UPDATE_COUPON_SUCCESS: 'UPDATE_COUPON_SUCCESS',
    UPDATE_COUPON_FAILURE: 'UPDATE_COUPON_FAILURE',

    GET_ALL_COUPONS_REQUEST: 'GET_ALL_COUPONS_REQUEST',
    GET_ALL_COUPONS_SUCCESS: 'GET_ALL_COUPONS_SUCCESS',
    GET_ALL_COUPONS_FAILURE: 'GET_ALL_COUPONS_FAILURE',

    GET_USER_COUPONS_REQUEST: 'GET_USER_COUPONS_REQUEST',
    GET_USER_COUPONS_SUCCESS: 'GET_USER_COUPONS_SUCCESS',
    GET_USER_COUPONS_FAILURE: 'GET_USER_COUPONS_FAILURE',

    DELETE_COUPON_REQUEST: 'DELETE_COUPON_REQUEST',
    DELETE_COUPON_SUCCESS: 'DELETE_COUPON_SUCCESS',
    DELETE_COUPON_FAILURE: 'DELETE_COUPON_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_COUPON: 'SELECT_COUPON',

};