export const couponPriceConstants = {
    ADD_COUPONPRICE_REQUEST: 'ADD_COUPONPRICE_REQUEST',
    ADD_COUPONPRICE_SUCCESS: 'ADD_COUPONPRICE_SUCCESS',
    ADD_COUPONPRICE_FAILURE: 'ADD_COUPONPRICE_FAILURE',

    UPDATE_COUPONPRICE_REQUEST: 'UPDATE_COUPONPRICE_REQUEST',
    UPDATE_COUPONPRICE_SUCCESS: 'UPDATE_COUPONPRICE_SUCCESS',
    UPDATE_COUPONPRICE_FAILURE: 'UPDATE_COUPONPRICE_FAILURE',

    GET_ALL_COUPONPRICES_REQUEST: 'GET_ALL_COUPONPRICES_REQUEST',
    GET_ALL_COUPONPRICES_SUCCESS: 'GET_ALL_COUPONPRICES_SUCCESS',
    GET_ALL_COUPONPRICES_FAILURE: 'GET_ALL_COUPONPRICES_FAILURE',

    GET_USER_COUPONPRICES_REQUEST: 'GET_USER_COUPONPRICES_REQUEST',
    GET_USER_COUPONPRICES_SUCCESS: 'GET_USER_COUPONPRICES_SUCCESS',
    GET_USER_COUPONPRICES_FAILURE: 'GET_USER_COUPONPRICES_FAILURE',

    GET_OMC_COUPONPRICES_REQUEST: 'GET_OMC_COUPONPRICES_REQUEST',
    GET_OMC_COUPONPRICES_SUCCESS: 'GET_OMC_COUPONPRICES_SUCCESS',
    GET_OMC_COUPONPRICES_FAILURE: 'GET_OMC_COUPONPRICES_FAILURE',

    DELETE_COUPONPRICE_REQUEST: 'DELETE_COUPONPRICE_REQUEST',
    DELETE_COUPONPRICE_SUCCESS: 'DELETE_COUPONPRICE_SUCCESS',
    DELETE_COUPONPRICE_FAILURE: 'DELETE_COUPONPRICE_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_COUPONPRICE: 'SELECT_COUPONPRICE',

};