export const currencyConstants = {
    ADD_CURRENCY_REQUEST: 'ADD_CURRENCY_REQUEST',
    ADD_CURRENCY_SUCCESS: 'ADD_CURRENCY_SUCCESS',
    ADD_CURRENCY_FAILURE: 'ADD_CURRENCY_FAILURE',

    UPDATE_CURRENCY_REQUEST: 'UPDATE_CURRENCY_REQUEST',
    UPDATE_CURRENCY_SUCCESS: 'UPDATE_CURRENCY_SUCCESS',
    UPDATE_CURRENCY_FAILURE: 'UPDATE_CURRENCY_FAILURE',

    GET_ALL_CURRENCIES_REQUEST: 'GET_ALL_CURRENCIES_REQUEST',
    GET_ALL_CURRENCIES_SUCCESS: 'GET_ALL_CURRENCIES_SUCCESS',
    GET_ALL_CURRENCIES_FAILURE: 'GET_ALL_CURRENCIES_FAILURE',

    GET_USER_CURRENCIES_REQUEST: 'GET_USER_CURRENCIES_REQUEST',
    GET_USER_CURRENCIES_SUCCESS: 'GET_USER_CURRENCIES_SUCCESS',
    GET_USER_CURRENCIES_FAILURE: 'GET_USER_CURRENCIES_FAILURE',

    GET_OMC_COUPON_CURRENCIES_REQUEST: 'GET_OMC_COUPON_CURRENCIES_REQUEST',
    GET_OMC_COUPON_CURRENCIES_SUCCESS: 'GET_OMC_COUPON_CURRENCIES_SUCCESS',
    GET_OMC_COUPON_CURRENCIES_FAILURE: 'GET_OMC_COUPON_CURRENCIES_FAILURE',

    DELETE_CURRENCY_REQUEST: 'DELETE_CURRENCY_REQUEST',
    DELETE_CURRENCY_SUCCESS: 'DELETE_CURRENCY_SUCCESS',
    DELETE_CURRENCY_FAILURE: 'DELETE_CURRENCY_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_CURRENCY: 'SELECT_CURRENCY',

};