export const locationConstants = {
    ADD_REQUEST: 'LOCATIONS_ADD_REQUEST',
    ADD_SUCCESS: 'LOCATIONS_ADD_SUCCESS',
    ADD_FAILURE: 'LOCATIONS_ADD_FAILURE',

    UPDATE_REQUEST: 'LOCATIONS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'LOCATIONS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'LOCATIONS_UPDATE_FAILURE',

    GETALL_REQUEST: 'LOCATIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'LOCATIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'LOCATIONS_GETALL_FAILURE',

    GETUSERLOCATION_REQUEST: 'LOCATIONS_GETUSERLOCATION_REQUEST',
    GETUSERLOCATION_SUCCESS: 'LOCATIONS_GETUSERLOCATION_SUCCESS',
    GETUSERLOCATION_FAILURE: 'LOCATIONS_GETUSERLOCATION_FAILURE',

    DELETE_REQUEST: 'LOCATIONS_DELETE_REQUEST',
    DELETE_SUCCESS: 'LOCATIONS_DELETE_SUCCESS',
    DELETE_FAILURE: 'LOCATIONS_DELETE_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_LOCATION: 'SELECT_LOCATION',

    PICK_LOCATION: 'PICK_LOCATION',
    GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION'
};