export const omcConstants = {
    ADD_OMC_REQUEST: 'ADD_OMC_REQUEST',
    ADD_OMC_SUCCESS: 'ADD_OMC_SUCCESS',
    ADD_OMC_FAILURE: 'ADD_OMC_FAILURE',

    UPDATE_OMC_REQUEST: 'UPDATE_OMC_REQUEST',
    UPDATE_OMC_SUCCESS: 'UPDATE_OMC_SUCCESS',
    UPDATE_OMC_FAILURE: 'UPDATE_OMC_FAILURE',

    GET_ALL_OMCS_REQUEST: 'GET_ALL_OMCS_REQUEST',
    GET_ALL_OMCS_SUCCESS: 'GET_ALL_OMCS_SUCCESS',
    GET_ALL_OMCS_FAILURE: 'GET_ALL_OMCS_FAILURE',

    GET_OMCS_WITH_COUPON_PRICES_REQUEST: 'GET_OMCS_WITH_COUPON_PRICES_REQUEST',
    GET_OMCS_WITH_COUPON_PRICES_SUCCESS: 'GET_OMCS_WITH_COUPON_PRICES_SUCCESS',
    GET_OMCS_WITH_COUPON_PRICES_FAILURE: 'GET_OMCS_WITH_COUPON_PRICES_FAILURE',

    GET_OMC_FUEL_PRICE_REQUEST: 'GET_OMC_FUEL_PRICE_REQUEST',
    GET_OMC_FUEL_PRICE_SUCCESS: 'GET_OMC_FUEL_PRICE_SUCCESS',
    GET_OMC_FUEL_PRICE_FAILURE: 'GET_OMC_FUEL_PRICE_FAILURE',

    GET_USER_OMCS_REQUEST: 'GET_USER_OMCS_REQUEST',
    GET_USER_OMCS_SUCCESS: 'GET_USER_OMCS_SUCCESS',
    GET_USER_OMCS_FAILURE: 'GET_USER_OMCS_FAILURE',

    DELETE_OMC_REQUEST: 'DELETE_OMC_REQUEST',
    DELETE_OMC_SUCCESS: 'DELETE_OMC_SUCCESS',
    DELETE_OMC_FAILURE: 'DELETE_OMC_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_OMC: 'SELECT_OMC',

};