export const paymentConstants = {
    PAYMENT_REQUEST: 'PAYMENT_REQUEST',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILURE: 'PAYMENT_FAILURE',

    POLL_REQUEST: 'POLL_REQUEST',
    POLL_SUCCESS: 'POLL_SUCCESS',
    POLL_FAILURE: 'POLL_FAILURE',

    WALLET_PAY_REQUEST: 'WALLET_PAY_REQUEST',
    WALLET_PAY_SUCCESS: 'WALLET_PAY_SUCCESS',
    WALLET_PAY_FAILURE: 'WALLET_PAY_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',
};