export const requestConstants = {
    ADD_REQUEST_REQUEST: 'ADD_REQUEST_REQUEST',
    ADD_REQUEST_SUCCESS: 'ADD_REQUEST_SUCCESS',
    ADD_REQUEST_FAILURE: 'ADD_REQUEST_FAILURE',

    UPDATE_REQUEST_REQUEST: 'UPDATE_REQUEST_REQUEST',
    UPDATE_REQUEST_SUCCESS: 'UPDATE_REQUEST_SUCCESS',
    UPDATE_REQUEST_FAILURE: 'UPDATE_REQUEST_FAILURE',

    GET_ALL_REQUESTS_REQUEST: 'GET_ALL_REQUESTS_REQUEST',
    GET_ALL_REQUESTS_SUCCESS: 'GET_ALL_REQUESTS_SUCCESS',
    GET_ALL_REQUESTS_FAILURE: 'GET_ALL_REQUESTS_FAILURE',

    GET_USER_REQUESTS_REQUEST: 'GET_USER_REQUESTS_REQUEST',
    GET_USER_REQUESTS_SUCCESS: 'GET_USER_REQUESTS_SUCCESS',
    GET_USER_REQUESTS_FAILURE: 'GET_USER_REQUESTS_FAILURE',

    GET_UNREAD_USER_REQUESTS_REQUEST: 'GET_UNREAD_USER_REQUESTS_REQUEST',
    GET_UNREAD_USER_REQUESTS_SUCCESS: 'GET_UNREAD_USER_REQUESTS_SUCCESS',
    GET_UNREAD_USER_REQUESTS_FAILURE: 'GET_UNREAD_USER_REQUESTS_FAILURE',

    DELETE_REQUEST_REQUEST: 'DELETE_REQUEST_REQUEST',
    DELETE_REQUEST_SUCCESS: 'DELETE_REQUEST_SUCCESS',
    DELETE_REQUEST_FAILURE: 'DELETE_REQUEST_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_REQUEST_REQUEST: 'SELECT_REQUEST_REQUEST',
    SELECT_REQUEST_SUCCESS: 'SELECT_REQUEST_SUCCESS',
    SELECT_REQUEST_FAILURE: 'SELECT_REQUEST_FAILURE', 

};