export const stationConstants = {
    ADD_STATION_REQUEST: 'ADD_STATION_REQUEST',
    ADD_STATION_SUCCESS: 'ADD_STATION_SUCCESS',
    ADD_STATION_FAILURE: 'ADD_STATION_FAILURE',

    UPDATE_STATION_REQUEST: 'UPDATE_STATION_REQUEST',
    UPDATE_STATION_SUCCESS: 'UPDATE_STATION_SUCCESS',
    UPDATE_STATION_FAILURE: 'UPDATE_STATION_FAILURE',

    GET_ALL_STATIONS_REQUEST: 'GET_ALL_STATIONS_REQUEST',
    GET_ALL_STATIONS_SUCCESS: 'GET_ALL_STATIONS_SUCCESS',
    GET_ALL_STATIONS_FAILURE: 'GET_ALL_STATIONS_FAILURE',

    GET_NEAREST_SERVICE_STATIONS_REQUEST: 'GET_NEAREST_SERVICE_STATIONS_REQUEST',
    GET_NEAREST_SERVICE_STATIONS_SUCCESS: 'GET_NEAREST_SERVICE_STATIONS_SUCCESS',
    GET_NEAREST_SERVICE_STATIONS_FAILURE: 'GET_NEAREST_SERVICE_STATIONS_FAILURE',

    SEARCH_NEAREST_SERVICE_STATIONS_REQUEST: 'SEARCH_NEAREST_SERVICE_STATIONS_REQUEST',
    SEARCH_NEAREST_SERVICE_STATIONS_SUCCESS: 'SEARCH_NEAREST_SERVICE_STATIONS_SUCCESS',
    SEARCH_NEAREST_SERVICE_STATIONS_FAILURE: 'SEARCH_NEAREST_SERVICE_STATIONS_FAILURE',

    GET_USER_STATIONS_REQUEST: 'GET_USER_STATIONS_REQUEST',
    GET_USER_STATIONS_SUCCESS: 'GET_USER_STATIONS_SUCCESS',
    GET_USER_STATIONS_FAILURE: 'GET_USER_STATIONS_FAILURE',

    GET_STATION_BY_CODE_REQUEST: 'GET_STATION_BY_CODE_REQUEST',
    GET_STATION_BY_CODE_SUCCESS: 'GET_STATION_BY_CODE_SUCCESS',
    GET_STATION_BY_CODE_FAILURE: 'GET_STATION_BY_CODE_FAILURE',

    GET_FUEL_PRICE_BY_STATION_CODE_REQUEST: 'GET_FUEL_PRICE_BY_STATION_CODE_REQUEST',
    GET_FUEL_PRICE_BY_STATION_CODE_SUCCESS: 'GET_FUEL_PRICE_BY_STATION_CODE_SUCCESS',
    GET_FUEL_PRICE_BY_STATION_CODE_FAILURE: 'GET_FUEL_PRICE_BY_STATION_CODE_FAILURE',

    DELETE_STATION_REQUEST: 'DELETE_STATION_REQUEST',
    DELETE_STATION_SUCCESS: 'DELETE_STATION_SUCCESS',
    DELETE_STATION_FAILURE: 'DELETE_STATION_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_STATION: 'SELECT_STATION',

};