export const transactionConstants = {

    GET_USER_TRANSACTIONS_REQUEST: 'GET_USER_TRANSACTIONS_REQUEST',
    GET_USER_TRANSACTIONS_SUCCESS: 'GET_USER_TRANSACTIONS_SUCCESS',
    GET_USER_TRANSACTIONS_FAILURE: 'GET_USER_TRANSACTIONS_FAILURE',

    GET_TRANSACTIONS_BY_WALLET_REQUEST: 'GET_TRANSACTIONS_BY_WALLET_REQUEST',
    GET_TRANSACTIONS_BY_WALLET_SUCCESS: 'GET_TRANSACTIONS_BY_WALLET_SUCCESS',
    GET_TRANSACTIONS_BY_WALLET_FAILURE: 'GET_TRANSACTIONS_BY_WALLET_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_TRANSACTION: 'SELECT_TRANSACTION',

};