export const walletConstants = {
    ADD_WALLET_REQUEST: 'ADD_WALLET_REQUEST',
    ADD_WALLET_SUCCESS: 'ADD_WALLET_SUCCESS',
    ADD_WALLET_FAILURE: 'ADD_WALLET_FAILURE',

    UPDATE_WALLET_REQUEST: 'UPDATE_WALLET_REQUEST',
    UPDATE_WALLET_SUCCESS: 'UPDATE_WALLET_SUCCESS',
    UPDATE_WALLET_FAILURE: 'UPDATE_WALLET_FAILURE',

    GET_ALL_WALLETS_REQUEST: 'GET_ALL_WALLETS_REQUEST',
    GET_ALL_WALLETS_SUCCESS: 'GET_ALL_WALLETS_SUCCESS',
    GET_ALL_WALLETS_FAILURE: 'GET_ALL_WALLETS_FAILURE',

    GET_USER_WALLETS_REQUEST: 'GET_USER_WALLETS_REQUEST',
    GET_USER_WALLETS_SUCCESS: 'GET_USER_WALLETS_SUCCESS',
    GET_USER_WALLETS_FAILURE: 'GET_USER_WALLETS_FAILURE',

    GET_WALLET_BY_CODE_REQUEST: 'GET_WALLET_BY_CODE_REQUEST',
    GET_WALLET_BY_CODE_SUCCESS: 'GET_WALLET_BY_CODE_SUCCESS',
    GET_WALLET_BY_CODE_FAILURE: 'GET_WALLET_BY_CODE_FAILURE',

    WALLET_PAY_STATION_REQUEST: 'WALLET_PAY_STATION_REQUEST',
    WALLET_PAY_STATION_SUCCESS: 'WALLET_PAY_STATION_SUCCESS',
    WALLET_PAY_STATION_FAILURE: 'WALLET_PAY_STATION_FAILURE',

    WALLET_TO_WALLET_TRANSFER_REQUEST: 'WALLET_TO_WALLET_TRANSFER_REQUEST',
    WALLET_TO_WALLET_TRANSFER_SUCCESS: 'WALLET_TO_WALLET_TRANSFER_SUCCESS',
    WALLET_TO_WALLET_TRANSFER_FAILURE: 'WALLET_TO_WALLET_TRANSFER_FAILURE',

    TOPUP_WALLET_MOBILE_PAYMENT_REQUEST: 'TOPUP_WALLET_MOBILE_PAYMENT_REQUEST',
    TOPUP_WALLET_MOBILE_PAYMENT_SUCCESS: 'TOPUP_WALLET_MOBILE_PAYMENT_SUCCESS',
    TOPUP_WALLET_MOBILE_PAYMENT_FAILURE: 'TOPUP_WALLET_MOBILE_PAYMENT_FAILURE',

    DELETE_WALLET_REQUEST: 'DELETE_WALLET_REQUEST',
    DELETE_WALLET_SUCCESS: 'DELETE_WALLET_SUCCESS',
    DELETE_WALLET_FAILURE: 'DELETE_WALLET_FAILURE',
    
    CLEAR: 'ALERT_CLEAR',

    SELECT_WALLET: 'SELECT_WALLET',

};