export const zesaConstants = {
    GET_CUSTOMER_DETAILS_REQUEST: 'GET_CUSTOMER_DETAILS_REQUEST',
    GET_CUSTOMER_DETAILS_SUCCESS: 'GET_CUSTOMER_DETAILS_SUCCESS',
    GET_CUSTOMER_DETAILS_FAILURE: 'GET_CUSTOMER_DETAILS_FAILURE',

    BUY_ZESA_TOKEN_REQUEST: 'BUY_ZESA_TOKEN_REQUEST',
    BUY_ZESA_TOKEN_SUCCESS: 'BUY_ZESA_TOKEN_SUCCESS',
    BUY_ZESA_TOKEN_FAILURE: 'BUY_ZESA_TOKEN_FAILURE',

    GET_TOKEN_REQUEST: 'GET_TOKEN_REQUEST',
    GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
    GET_TOKEN_FAILURE: 'GET_TOKEN_FAILURE',

    CLEAR: 'ALERT_CLEAR',
};